### ISSUE TITLE
Missing return statement for click_needle()?

### ISSUE THREAD

**Issue by a-rokay** [takelley1/OCVBot#13]
I noticed `click_needle()` doesn't return anything, only raises an exception if the needle isn't found. I'm assuming this isn't intended.

**Comment by takelley1** [comment]
I've been doing some refactoring and this is intended. Using exceptions to manage logic flow is more Pythonic than using True/False return values, so I've been making a transition.

The primary benefit of exception-based control flow is you no longer have to check if the return value of a function is `False` before continuing. If you want a failed function to halt the program, simply call it and let it raise an exception. If not, then handle the exception in a `try`/`except` block. I think this generally makes the code cleaner and adheres more to best-practices, though I'm definitely open to opposing views.

**Comment by a-rokay** [comment]
I see, thanks for the info.
