### ISSUE TITLE
[Request] Add "How to" guide for created additional scenarios

### ISSUE THREAD

**Issue by crwgregory** [takelley1/OCVBot#16]
Would be sweet. I've just been digging through the code, would be nice to have an "official" post about it.

**Comment by takelley1** [comment]
Are you interested in adding a scenario for a skill that's already supported? To add a scenario to the mining behavior, for example, you just have to add the [relevant block](https://github.com/takelley1/OCVBot/blob/477c2a0965a70e5a935ea9a52fb26193b0e8ec76/ocvbot/main.py#L86), then add any necessary [needle images](https://github.com/takelley1/OCVBot/tree/main/ocvbot/needles/game-screen/varrock-east-mine). If you want to bank the ore, you'll have to add a [haystack map for the area](https://github.com/takelley1/OCVBot/blob/main/ocvbot/haystacks/varrock-east-mine.png) and add the [relevant parameters](https://github.com/takelley1/OCVBot/blob/477c2a0965a70e5a935ea9a52fb26193b0e8ec76/ocvbot/main.py#L101) to get the character to the bank and back
