### ISSUE TITLE
Add switch_worlds_logged_out() Function

### ISSUE THREAD

**Issue by a-rokay** [takelley1/OCVBot#7]
I noticed TODO for a `switch_worlds_logged_out()` function. I'd like to try implementing this.

![image](https://user-images.githubusercontent.com/86167097/140247693-b4538e05-4afe-4a09-b299-70cf60917c0f.png)

Since the world selector is a grid, I'm thinking of writing a separate script that could live in `tools/` that parses the [world page](https://oldschool.runescape.com/a=13/slu?order=WMLPA) for worlds and stores their attributes (type, requirements, pvp) in a json file. Each world could have it's own `row` and `column` values that dictate it's placement on the world selector. 

```json
"301": {
	"p2p": false,
	"pvp": false,
	"skill_req": "None",
	"row": 1,
	"col": 1
}
```

Using an offset, we could get accurate coordinates on the client. If the column value is out of bounds (>7), the "next page" button could be pressed before selecting the world. Thoughts on this?

**Comment by takelley1** [comment]
Interesting idea. I'm definitely open to it!

Once thing you'd have to make sure of is that no filters are being applied in the world selector page on the game client, as that would change the ordering of the list. It seems fairly simple to fix though: if the downward-pointing arrow next to the `World` filter isn't green, then click it.

I'm not sure what the best way to parse that webpage would be, though -- it's too bad they don't offer an API for this sort of thing. I don't have much experience with web scraping in Python, so hopefully I'll learn something new by seeing what you come up with!

**Comment by a-rokay** [comment]
Would you like me to submit a separate pr for the scraper?

**Comment by a-rokay** [comment]
I'll submit the scraper in a separate Pr.
